language: java
env:
  global:
    - CC_TEST_REPORTER_ID=a6d28a48f26dab9b351871ab95c0ecc9ca25c4eaa6ad106a8f1b2ce7ce80a0cc
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug
script:
# Use X Virtual Framebuffer to imitate display for GUI tests
# Force Cobertura to generate an XML report (so Code Climate test-reporter can process it)
  - xvfb-run --server-args="-screen 0 1920x1080x24" mvn cobertura:cobertura -Dcobertura.report.format=xml
after_script:
# Point test-reporter to the XML coverage report from Cobertura
  - ./cc-test-reporter format-coverage --input-type cobertura target/site/cobertura/coverage.xml --debug
  - ./cc-test-reporter upload-coverage --debug