language: java
env:
  global:
    - CC_TEST_REPORTER_ID=1020bb9827336a6004e9890ac0e77fd15febbba2992939dbe081dcd02fa9f17a
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug
script:
  - mvn cobertura:cobertura
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug